version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: no
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: k8s_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: ..
    container_name: node_app
    restart: no
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: k8s_db
      DB_PORT: 5432
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: [ "node", "src/server.js" ]

volumes:
  pgdata:
